# Generated by Django 4.2 on 2025-04-11 01:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saludo', models.CharField(max_length=100, verbose_name='Saludo (ej. ¡Hola!)')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='home/', verbose_name='Imagen principal')),
                ('texto_boton', models.CharField(default='Más sobre mí', max_length=50, verbose_name='Texto del botón')),
                ('enlace_boton', models.URLField(default='/about', verbose_name='Enlace del botón')),
            ],
            options={
                'verbose_name': 'Contenido de Inicio',
                'verbose_name_plural': 'Contenido de Inicio',
            },
        ),
    ]
