# Generated by Django 4.2 on 2025-04-11 02:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('freelance', models.BooleanField(default=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('skype', models.CharField(max_length=100)),
                ('idiomas', models.CharField(max_length=200)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'Sobre mí',
                'verbose_name_plural': 'Sobre mí',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.PositiveIntegerField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('anio', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('anio', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.aboutme')),
            ],
        ),
    ]
