# Generated by Django 4.2 on 2025-04-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutme_stat_skill_experience_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del proyecto')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('lenguajes', models.CharField(max_length=200, verbose_name='Lenguajes/tecnologías')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Enlace del proyecto')),
                ('imagen', models.ImageField(upload_to='portfolio/', verbose_name='Imagen destacada')),
                ('descripcion', models.TextField(verbose_name='Descripción del proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto de Portafolio',
                'verbose_name_plural': 'Proyectos de Portafolio',
            },
        ),
    ]
