# Generated by Django 4.2 on 2025-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portfolioproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='Archivo CV (PDF)'),
        ),
    ]
