# Generated by Django 4.2 on 2025-04-11 13:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutme_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Get in touch', max_length=200)),
                ('subtitulo', models.CharField(default='Contact', max_length=200)),
                ('mensaje_intro', ckeditor.fields.RichTextField(verbose_name='Mensaje introductorio')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('telefono', models.CharField(max_length=50, verbose_name='Número de teléfono')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('dribbble', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Información de contacto',
                'verbose_name_plural': 'Información de contacto',
            },
        ),
    ]
