# Generated by Django 4.2 on 2025-04-11 15:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogcategory_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Imagen')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción corta')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('tags', models.CharField(max_length=200, verbose_name='Etiquetas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('author', models.CharField(default='admin', max_length=100, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blogcategory', verbose_name='Categoría')),
            ],
        ),
    ]
