# Generated by Django 4.2 on 2025-05-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'verbose_name': 'Estadística', 'verbose_name_plural': 'Estadísticas'},
        ),
    ]
