# Generated by Django 4.2 on 2025-05-03 15:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_blogpost_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción del proyecto'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
