# Generated by Django 4.2 on 2025-05-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_portfolioproject_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Categoría de blog', 'verbose_name_plural': 'Categorías de blog'},
        ),
    ]
